<?php
/** @var Amasty\VictoriaModule\Block\Index $block */
?>

<div>
    <form id="addProduct" action="<?= $block->getFormAction(); ?>" method="post" data-mage-init='{"validation":{}}'>
        <div class="<?=$block->getData("input_class_sku"); ?>" data-bind="scope: 'skuAutocomplete'">
        <!-- ko template: getTemplate() --> <!-- /ko -->
        </div>
        <div class="<?= $block->setVisibleElement(); ?> ">
                <label for="qty">Qty:</label>
                <input type="number" name="qty" id="qty" value="<?=$block->getQtyDefault() ?>"
                       data-validate='{"required":true, "min":1}'>
        </div>
    </form>
    <div class="<?=$block->getData('timer_class') ?>">
        <?=$block->getChildHtml('amasty_victoriamod.timer'); ?>
    </div>
    <div>
        <button form="addProduct" class="<?=$block->getData("input_class_submit"); ?>">Submit</button>
    </div>

</div>


<script type="text/x-magento-init">
    {
    "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "skuAutocomplete": {
                        "component": "Amasty_VictoriaModule/js/skuAutocomplete",
                        "template": "Amasty_VictoriaModule/skuAutocomplete"
                    }
                }
            }
        }
    }
</script>
