<script type="text/x-magento-init">
    {
    "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "displayTimer": {
                        "component": "Amasty_VictoriaModule/js/timer",
                        "template": "Amasty_VictoriaModule/timer"
                    }
                }
            }
        }
    }
</script>

<div data-bind="scope: 'displayTimer'">
    <!-- ko template: getTemplate() --> <!-- /ko -->
</div>
